#:schema ./_schema.json
[user]
name = "David Barnett"
email = "{{ env.VCS_AUTHOR_EMAIL }}"

[ui]
editor = "nvim"
merge-editor = "meld"
graph.style = "curved"
pager = "delta"
diff.format = "git"

[revset-aliases]
'mine' = "author(\"{{ env.VCS_AUTHOR_EMAIL }}\") | author(dbarnett) | author(davidbarnett)"
'user(x)' = 'author(x) | committer(x)'
'off(x)' = 'x.. | ((x..)- & :x)'
'default(n)' = '@ | ancestors(immutable_heads().., n) | trunk()'

[git]
private-commits = "description(glob:'wip:*') | description(glob:'private:*')"
